### ISSUE TITLE
Best way to redraw slider after screen resize?

### ISSUE THREAD

**Issue by studioleland** [NUKnightLab/juxtapose#115]
I am using the javascript implementation with "makeResponsive: true" feature.  When screen resizes the slider does not respond.  Is there a manual redraw method I can use to reinitialize slider on screen resize?

**Comment by JoeGermuska** [comment]
@studioleland `makeResponsive` doesn't automatically resize the slider -- that's up to the CSS in your own page. If you change the dimensions of the slider's container, the slider should adjust correctly. Add CSS media queries to resize the slider container.

To clarify, `makeResponsive` is used when the slider is in an iframe. We can't simply scale images to fill the iframe, because it interferes with alignment, so we try to "letter box" it if the iframe dimensions don't match the image dimensions. It's pretty complicated, and maybe there's a better way to do it we haven't thought of yet.

Hope this clarifies things.

**Comment by madhaze** [comment]
possible workaround documented on #105
