### ISSUE TITLE
Juxtapose keeps disappearing

### ISSUE THREAD

**Issue by xsimtomx** [NUKnightLab/juxtapose#133]
I created a Juxtapose and then used the generated link (iframe) to embed it on my website but after a while (hours) it just disappears. 

Is there anything I can do about this? You can find my website [here](http://users.telenet.be/kalaman). 

Many thanks!

**Comment by JoeGermuska** [comment]
Let me note that generally, we'd prefer to handle questions like this through our [support request system](https://knightlab.zendesk.com/hc/en-us/requests/new), but since you asked here, we can answer here.

You are using imgur.com for image hosting. imgur has begun aggressively blocking direct image linking (hotlinking) on other non-forum websites. It is returning 403 (forbidden) status when Juxtapose requests those images.  I can't say why it works temporarily, but as far as we can tell, Imgur's policies are at odds with using it to host images for JuxtaposeJS. 

[This tweet](https://twitter.com/imgur/status/879408405403664384?lang=en) is the closest thing I can find to an official Imgur statement on it.

The solution is to find another place to host your images. Unfortunately, most free image hosting services are cracking down on hotlinking, because it effectively cuts them out of any value they get for providing the service.  At this time, Flickr and Dropbox are two services which we know work, and of course, if you have your own webserver, you should be able to put the images on that server.

**Comment by xsimtomx** [comment]
I'm sorry about posting this here, I'm quite new to Juxtapose.

Now I understand why I wasn't seeing it on mobile devices and why it kept disappearing. From now on I'll use Dropbox.

Thanks for explaining, Joe!

**Comment by miklide** [comment]
@JoeGermuska Aahhhh, that's what was causing it. Thank you. May be include tip about hotlinking dangers somewhere in FAQ at main page?
