### ISSUE TITLE
XSS when using data-credit

### ISSUE THREAD

**Issue by cnsgithub** [NUKnightLab/juxtapose#137]
**What's the problem?**
The user-supplied `data-credit `attribute is not properly escaped. This makes juxtapose vulnerable to DOM-XSS.

**How to reproduce?**
1. Use the sample code below and hover the strikethrough _foo_ credit label. An alert box will arise.
```html
<div class="juxtapose">
    <img src="https://juxtapose.knightlab.com/static/img/Sochi_11April2005.jpg" />
    <img src="https://juxtapose.knightlab.com/static/img/Sochi_22Nov2013.jpg" data-credit="&lt;strike onmouseover=&quot;alert('xss');&quot;&gt;foo&lt;/b&gt;" />
</div>
<script src="https://cdn.knightlab.com/libs/juxtapose/latest/js/juxtapose.min.js"></script>
<link rel="stylesheet" href="https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css">
```

Or alternatively,

2. Go to https://juxtapose.knightlab.com/#preview-embed and enter `<strike onmouseover="alert('xss');">foo</b>` as credit label. Click at the _Preview_ button. Hover the strikethrough _foo_ credit label in the rendered output. An alert box will arise.

![image](https://user-images.githubusercontent.com/13161711/42268715-880e623a-7f7c-11e8-86fb-8be825c50445.png)

**Comment by cnsgithub** [comment]
PR: https://github.com/NUKnightLab/juxtapose/pull/138

**Comment by JoeGermuska** [comment]
We have, historically, considered this an author's problem, and opted for more flexibility for authors rather than more constraints. That is, the only time that a user is supplying HTML which could be malicious is using our authoring tool, where the only victim is that user. Once the embed is published, it's published on a page which the author already controls, where if they were trying to compromise a viewer, they have many options.

Also, to be honest, the "credit" feature is informally deprecated, as it's not internationalized and the effort to internationalize it is too high when there's a simpler workaround of simply not using it and encouraging creators to provide the credit in the host page outside of the embed.

Marking as #wontfix but am open to further discussion if we're seriously mistaken.

**Comment by cnsgithub** [comment]
Well, the problem is that you provide your library on github under a user-friendly license. Therefore you have to expect that other projects/libraries (e.g. https://github.com/primefaces/primefaces, a popular and widely used JSF library) include it. And there is no control what they in turn are providing to their users, e.g. they may let their users upload images with the ability to leave credits. Those may be persisted in database and presented to other users that may then be affected as well. As far as I know there is no juxtapose API documentation saying that the user must escape credits because juxtapose lacks to do so?

Depending on the website juxtapose is embedded the impact can be very high. Imagine a superuser is currently logged in and visits the site. Then the session could be hijacked by sending the cookies to a prepared URL. Or the attacker could redirect you to a malicious site. Or the website could be defaced. Or CSRF protection could be bypassed. And so on...

After that being said I think that you have to take responsibility when providing a library. If you don't care, please do not make it publicly available. The internet is full of vulnerabilities. We should try to just making it a bit better. And you can help.

When you're saying `data-credit `is deprecated why not remove it? Otherwise please do not allow HTML (you're welcome to merge my PR) or at least sanitize it by only allowing _safe_ tags.

Did you try this one: https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=0186526e-80de-11e8-b263-0edaf8f81e27? Hover the _CLICK ME_ link and see how your cookie got disclosed to disney.com. Puh, fortunately you have not been logged in on an atomic power plant and admin privileges. And disney.com is not malicious... Admittedly a little over the top... Just to make you wake up...

I'm voting for re-opening this issue, merging the PR and releasing a new version. Thanks.

**Comment by cnsgithub** [comment]
@JoeGermuska Did you think about it?

**Comment by JoeGermuska** [comment]
@cnsgithub yes. upon further review, we continue to believe that it is responsible for us to leave HTML sanitization to tools which build upon JuxtaposeJS, rather than implementing our own choices about that in the tool. 

Of course, if you feel that the sanitization should be implemented in the library, instead of in tools which use the library, the license on JuxtaposeJS doesn't prevent you from doing that in your own derivative.

Thanks for taking the time to open this discussion, and for sharing our tools with your community.

**Comment by cnsgithub** [comment]
Thanks for fixing it at least in the documentation.
