### ISSUE TITLE
facebook og:issues

### ISSUE THREAD

**Issue by sibalonat** [NUKnightLab/juxtapose#160]
guys these are the error that facebook shows when trying to share the link.
![image](https://user-images.githubusercontent.com/34999323/64984689-a3cf3980-d8c3-11e9-9c14-03f9872e1fde.png)

**Comment by JoeGermuska** [comment]
The simple free hosting provided by JuxtaposeJS does not provide any control over Opengraph tags because it uses the same HTML page (with different data) for all cases.  

We are working on an update to JuxtaposeJS which makes some changes to this, and which should provide a better social sharing experience.  At this time, I can't project when that will be released, but soon enough that this issue won't be addressed in the current version.
