### ISSUE TITLE
Lots of white space on mobile

### ISSUE THREAD

**Issue by graphicco** [NUKnightLab/juxtapose#164]
![WhatsApp Image 2020-01-22 at 19 22 28](https://user-images.githubusercontent.com/60194429/72922495-6e44cc00-3d4d-11ea-914c-f8c1bee2b217.jpeg)

![WhatsApp Image 2020-01-22 at 19 33 14](https://user-images.githubusercontent.com/60194429/72922841-1490d180-3d4e-11ea-8acb-b792914b5dad.jpeg)

on the computer it looks fine, but on mobile it shows a lot of white space under the embed code.
i thought it had something to do with my website configuration, but also when visiting the juxtapose website on my phone i noticed a lot of white space

i would love to use this embed code, but i was wondering if the white space can be reduced on mobile?

thanks

**Comment by brymonster** [comment]
found the same here.

**Comment by sacgrover** [comment]
You need to control height of iframe dynamically

**Comment by scott2b** [comment]
@sacgrover is correct. Because Juxtapose maintains the original aspect ratio of the images, and because it is embedded with an iframe, there is not a one-size-fits-all solution for handling multiple viewport sizes. The iframe size will need to be dynamically sized to accommodate the varying image sizes.

This can be handled either with Javascript, or bit less gracefully with media queries. Examples of both approaches are provided as "whitespace-fix" files in the examples folder: https://github.com/NUKnightLab/juxtapose/tree/master/examples

**Comment by Jorty-create** [comment]
how to fix this issue on Behance? As there only embedding is allowed of an iframe and no scripts.
