### ISSUE TITLE
local file upload

### ISSUE THREAD

**Issue by Vijay-Cre** [NUKnightLab/juxtapose#182]
hey thanks so much for creating such helpful tools and make things easy, really appreciated, but you didn't provide the option to upload a direct local file
![image](https://user-images.githubusercontent.com/129935511/230011286-dde8bb72-65be-4eee-9bd7-1ab8607634ec.png)

and I created a gif that was also wonderful except for the quality of the gif 
![image](https://user-images.githubusercontent.com/129935511/230011586-a16ae7a2-3df5-453d-a7d5-225fca53b2c4.png)
look it changes the quality that seems like vector art, and also so much pixelating, while animation 

here is gif 

![juxtapose-gif](https://user-images.githubusercontent.com/129935511/230011810-c8959508-9c08-425c-a779-b9317681b9e7.gif)

thanks for your effort people like you(creators) make life interesting!!!

**Comment by JoeGermuska** [comment]
Correct, there is no upload for the interactive/javascript based version. We are an academic lab with no revenue, and the cost of providing the tools we provide is already considerable. We chose to leave the image hosting for interactive Juxtapose as a responsibility for creators, rather than absorb the cost of permanently storing images for people.

For the animated gifs, yes, the image quality is substantially impacted. This is in part because the GIF file format has limited color range, and also because animated GIF files can be very large. We chose the settings we use in an attempt to optimize the output.

It may be that there are other settings which provide a different compromise, and as this GitHub repository bears out, the code is available for other people to experiment with. If someone can provide evidence of different settings that would produce reasonably sized GIFs, we would accept a pull request to change the current system.
