### ISSUE TITLE
Photos stack but don't slide

### ISSUE THREAD

**Issue by ElkhartTruthAnneC** [NUKnightLab/juxtapose#44]
The sliding tool doesn't appear and images are stacked one on top of the other. Help!

![screen shot 2015-03-11 at 3 22 09 pm](https://cloud.githubusercontent.com/assets/11429556/6604933/7a269582-c802-11e4-86c2-68e0bb309c53.png)

**Comment by duner** [comment]
Hi! Can you give us a bit more information on how you got this bug to happen? Where are you trying to embed Juxtapose? What browser (and what version) are you using?

**Comment by ElkhartTruthAnneC** [comment]
When I copy/paste the given code into the story file's HTML, the photos appear one on top of the other and there's no option to slide. I followed the instructions by first placing the first set of code:
<div class="juxtapose" data-startingposition="50" data-showlabels="true" data-showcredits="true" data-animate="true" data-mode="horizontal">
<img src="http://juxtapose.knightlab.com/static/img/Sochi_11April2005.jpg" data-label="Apr. 2005" data-credit="">
<img src="http://juxtapose.knightlab.com/static/img/Sochi_22Nov2013.jpg" data-label="Nov. 2013" data-credit="">
</div>

Then I place the second set of code below it:
<link rel="stylesheet" href="//s3.amazonaws.com/cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css"><script type="text/javascript" src="//s3.amazonaws.com/cdn.knightlab.com/libs/juxtapose/latest/js/juxtapose.js"></script>

And this is the result:
[cid:C8D404A1-7627-497D-940D-04B152E6674A]
Please let me know of other information I can give you to help with the bug.

Thanks for your quick response!

Anne Christnovich
Assistant managing editor
The Elkhart Truth

**Comment by duner** [comment]
Are you pasting it into an HTML file? Into a CMS like WordPress?

**Comment by ElkhartTruthAnneC** [comment]
We use a CMS called Libercus — the "normal" interface isn't where we put HTML but it has an HTML file that we use to write or place any HTML codes.

**Comment by duner** [comment]
So the view that you are getting is the fallback for when Juxtapose's JavaScript doesn't load.

Is it a published project, or are you viewing it locally in some kind of preview mode? If it is local, the JavaScript might be looking for `file://s3.amazon[...]` instead of  `http://s3.amazon[...]`. If it's published somewhere, is it possible that your CMS is stripping out the script tags? When you inspect the images, what is the code that you see?

**Comment by ElkhartTruthAnneC** [comment]
It doesn't *appear* to be scrubbing the tags... but admittedly, I'm not super practiced at spotting these kinds of issues. 
![screen shot 2015-03-11 at 5 00 01 pm](https://cloud.githubusercontent.com/assets/11429556/6606762/3fc74590-c810-11e4-8897-8de82a1df3a3.png)

**Comment by ElkhartTruthAnneC** [comment]
(that's the published story, btw. We have it on a live testing page right now.)

**Comment by duner** [comment]
It looks like you are missing (or your CMS is stripping) the `<script type="text/javascript" src="http://s3.amazonaws.com/cdn.knightlab.com/libs/juxtapose/latest/js/juxtapose.js"></script>` from your HTML. So that seems to be why it's not working for you.

One thing I'm curious about is why the link to the CSS is wrapped in <p> tags; I'm not sure that's affecting how Juxtapose works but it's not really necessary.

**Comment by duner** [comment]
Also, someone noticed that you have the link to your CSS wrapped in a `script` when it should be wrapped in a `link` like it is in the code you copy from the Juxtapose website. Fixing that might fix your problem as well.
