### ISSUE TITLE
Responsive Problems

### ISSUE THREAD

**Issue by duner** [NUKnightLab/juxtapose#7]
![Oops.](https://cloud.githubusercontent.com/assets/2475973/3197002/023c8832-ed3e-11e3-806a-3f282bfe4a60.png)

**Comment by peaceprop** [comment]
No problems on a Desktop, but on a mobile device (at least iOS) the frame doesn't scale down, so only a portion of the image is visible (see attached). Apologies if someone already posted on this, I tried to scour everything first. Any help is much appreciated. 

![img_7583](https://cloud.githubusercontent.com/assets/13918848/9424663/aa7d9ae0-48b9-11e5-8889-eaed715467ca.PNG)

**Comment by JoeGermuska** [comment]
@peaceprop Please provide a URL demonstrating the specific issue.

**Comment by peaceprop** [comment]
@JoeGermuska http://oneeleveneast.com/blog-mock/the-old-new-111-east-street

thanks for such a quick reply!

**Comment by JoeGermuska** [comment]
The problem is that we haven't yet settled on an ideal way to adapt the Juxtapose slider, which has two images (which may not have the same aspect ratios, although yours do) to a changing viewport, which itself may not have an aspect ratio which matches the given images.

Basically, we need to implement a letterboxing effect to float the slider in the available space with padding on the sides or the top/bottom depending upon how the aspect ratio of the Juxtapose slider relates to the container. (We've pretty much settled on using the aspect ratio of the first image as the aspect ratio for the whole slider, just because a choice had to be made.)

Then also we have to figure out how best set the iframe width/height attributes for people using the "authoring tool" so that they don't have to think about it -- but right now we're using absolute pixel width, which is itself not responsive.

So, reopening, because there's still work to do!

**Comment by hbillings** [comment]
Letterboxing is implemented, but the authoring tool still uses absolute pixel widths. Users must set the width to 100% for letterboxing to take effect.

I think it might be helpful to add width/height input boxes to the options. Editing one could automatically calculate the other based on the images' aspect ratios. And we could default the width to 100% to make it easier for people who want responsive sliders. Thoughts?

**Comment by JoeGermuska** [comment]
i appreciate the intention. What will we put in the "height" box when the width is "100%"? There's no such thing as "100%" height, right? Would we suppress the height attribute?

It may simply be better to set the width to 100%, leave the height out, and don't trouble the average user?

**Comment by hbillings** [comment]
Good point. Since the internals currently don't require user input of any kind, I was thinking we'd do the same calculations we do now for width and height when the width is 100%. Allowing the user to specify would just make it a little easier if you want to specifically set one or the other. (Mainly, I'm not sure everyone wants a 100% width slider, but if we set that as the width automatically, we're making people who want absolute widths manually figure out how to maintain a given aspect ratio.)

**Comment by hbillings** [comment]
(To clarify, I'm mostly talking about what values we put in the iframe embed code we generate and less about changing the functionality of Juxtapose.)

**Comment by JoeGermuska** [comment]
I understand your clarification. I'm just not sure what's the right answer! Maybe instead have a "responsive" checkbox, and if it's checked, have it be width 100%, and it's not, the current behavior?

**Comment by hbillings** [comment]
Ha, that was actually my first thought, and then I thought maybe it wasn't flexible enough.

**Comment by peaceprop** [comment]
Thank you so much for your time and expertise on this question. So, what happened in the end, did you find a solution?  Will the creator form be updated (or has it already?) Would love to know, thanks!

**Comment by hbillings** [comment]
@peaceprop Fixed but not publicly available yet (pending testing). You'll probably need to regenerate and re-embed your juxtapose in order for it to reflect the changes.

**Comment by hbillings** [comment]
@peaceprop Fixes have been pushed to juxtapose.knightlab.com
